import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true, args: ["--use-gl=angle", "--use-angle=swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
const logs = [];
page.on("pageerror", e => errors.push("PE:"+e.message));
page.on("console", m => { if (m.type()==="error") logs.push(m.text()); });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle", timeout: 20000 }).catch(()=>{});
await page.waitForTimeout(3000);
console.log("PHASE1", (await page.innerText("body")).slice(0,150));
const buttons = await page.locator("button").allTextContents();
console.log("BUTTONS", buttons);
const theo = page.getByRole("button", { name: /Theo Daniel/i });
console.log("theo count", await theo.count());
if (await theo.count()) await theo.click();
await page.waitForTimeout(600);
console.log("PHASE2", (await page.innerText("body")).slice(0,150));
const deploy = page.getByRole("button", { name: /Deploy to surface/i });
console.log("deploy", await deploy.count());
if (await deploy.count()) await deploy.click();
await page.waitForTimeout(6000);
console.log("PHASE3", (await page.innerText("body")).slice(0,400));
console.log("canvas", await page.locator("canvas").count());
console.log("errors", errors);
console.log("logs", logs.slice(0,10));
await browser.close();
